version: "3.5"

services:
  mongo:
    image: mongo:5
    container_name: darajaApi
    ports:
      - 27080:27017
    networks:
      - daraja
    volumes:
      - mongo:/data/db

networks:
  daraja:
    name: daraja-network

volumes:
  mongo:
    driver: local