server:
  port: 8080
mpesa:
  daraja:
    consumer-key: HFEJIgcmyUvUtQC5XvavNyqre55TxzkI
    consumer-secret: yWUDLDMxsalwbAc1
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
    shortCode: 123456
    confirmationURL: http://cc1a-196-207-137-127.ngrok.io/mobile-money/confirmation
    validationURL: http://cc1a-196-207-137-127.ngrok.io/mobile-money/validation
    responseType: Completed
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://279eba87a32e.ngrok.io/mobile-money/transaction-result
    b2c-queue-timeout-url: https://279eba87a32e.ngrok.io/mobile-money/b2c-queue-timeout
    b2c-initiator-name: apiop37
    b2c-initiator-password: Safaricom3021#
    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
    checkAccountBalanceUrl: https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query
    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    stkPushShortCode: 174379
    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkPushRequestCallbackUrl: https://localhost:8080/mobile-money/stk-transaction-result
    lnmQueryRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query

spring:
  data:
    mongodb:
      host: localhost
      port: 27080
      database: darajaApi